name = "nuxt-app"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2022-09-10"
account_id = "52ac24ef2fdc78361c257a94f2b294b3"
route = "chihyungchang.com"

[site]
bucket = ".output/public"